name: Release
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retag image
        run: |-
          echo "SHA $GITHUB_SHA, TAG: $GITHUB_REF"
          REF=$(echo $GITHUB_REF|sed 's/refs\/tags\///g')
          docker pull michalmarszalek/alpine-utils:sha-${GITHUB_SHA:0:7}
          docker tag michalmarszalek/alpine-utils:${GITHUB_SHA:0:7} michalmarszalek/alpine-utils:latest
          docker tag michalmarszalek/alpine-utils:${GITHUB_SHA:0:7} michalmarszalek/alpine-utils:$REF
          docker push michalmarszalek/alpine-utils:latest
          docker push michalmarszalek/alpine-utils:$REF