name: Release
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retag image
        env:
          IMAGE_NAME: michalmarszalek/jenkins-worker
        run: |-
          echo "SHA $GITHUB_SHA, TAG: $GITHUB_REF, EVENT: $GITHUB_EVENT_NAME"
          REF=$(echo $GITHUB_REF|sed 's/refs\/tags\///g')
          docker pull $IMAGE_NAME:sha-${GITHUB_SHA:0:7}
          docker tag $IMAGE_NAME:sha-${GITHUB_SHA:0:7} $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:sha-${GITHUB_SHA:0:7} $IMAGE_NAME:$REF
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$REF